# Custom Chatbot Project

Dataset: Character_description.

The dataset contains the description of various characters of plays, movies and limited series along with the settings of the same.

## Data Wrangling

In the cells below, I have loaded a chosen dataset into a `pandas` dataframe with a column named `"text"`. This column contains all of the text data, separated into at least 20 rows.

In [35]:
import pandas as pd
data=pd.read_csv('data/character_descriptions.csv')
df = pd.DataFrame()
df["text"]=data['Description']
df

                                                 text
0   A young woman in her early 20s, Emily is an as...
1   A middle-aged man in his 40s, Jack is a succes...
2   A woman in her late 30s, Alice is a warm and n...
3   A man in his 50s, Tom is a retired soldier and...
4   A woman in her mid-20s, Sarah is a free-spirit...
5   A man in his early 30s, George is a charming a...
6   A woman in her late 20s, Rachel is a shy and i...
7   A man in his 60s, John is a retired professor ...
8   A middle-aged Latina woman in her 40s, Maria i...
9   A young African American man in his early 20s,...
10  A white man in his mid-30s, Tyler is a tough-a...
11  A white woman in her late 20s, Sonya is a free...
12  A middle-aged Hispanic man in his 50s, Manuel ...
13  A white man in his early 40s, Will is a succes...
14  A young Australian woman in her mid-20s, Mia i...
15  A middle-aged Australian man in his 40s, Lucas...
16  A young Indigenous Australian woman in her ear...
17  A white Australian man in his late 20s, Max is...
18  A middle-aged Australian woman in her 50s, Ava...
19  A seasoned performer with a larger-than-life p...
20  A young up-and-coming performer, Johnny is ful...
21  A sultry and dramatic performer, Sable exudes ...
22  A bubbly and vivacious performer, Dolly is a f...
23  A fierce and competitive performer, Vixen is a...
24  A chameleon-like performer, Karma is known for...
25  A quirky and imaginative performer, Crystal is...
26  A confident and charismatic marketing executiv...
27  A charming and successful entrepreneur, Marcus...
28  A kind and compassionate nurse with a heart of...
29  A handsome and athletic personal trainer, Jame...
30  A fun-loving and adventurous travel blogger, S...
31  A quirky and creative graphic designer, Noah i...
32  A driven and ambitious attorney, Chloe is alwa...
33  A laid-back and easygoing firefighter, Jake is...
34  A charming and handsome prince who has recentl...
35  A mysterious and alluring woman who runs a loc...
36  A wealthy and arrogant nobleman who loves to f...
37  A fiery and passionate young woman who works a...
38  A charming and charismatic young man who is of...
39  A pompous and self-important nobleman who is h...
40  A wealthy and beautiful noblewoman who has rec...
41  A drunken and lecherous knight who loves nothi...
42  A pompous and self-righteous steward in Lady O...
43  A plucky and resourceful young woman who is sh...
44  A dim-witted and gullible nobleman who is brou...
45  Lady Olivia's cunning and quick-witted maid. B...
46  Viola's twin brother, who is also shipwrecked ...
47  A jester and musician who works in Lady Olivia...
48  A sea captain who rescues Sebastian from the s...
49  A plucky and resourceful young woman who works...
50  A good-natured and affable young man who also ...
51  The pious and stern minister of the local chur...
52  The charismatic and dashing captain of the loc...
53  The matriarch of the wealthiest family in Will...
54  The bumbling and absent-minded patriarch of th...

In [33]:
import openai
openai.api_key = 'API_KEY'

In [3]:
EMBEDDING_MODEL_NAME="text-embedding-ada-002"
response = openai.Embedding.create(
    input=df["text"].tolist(),
    engine=EMBEDDING_MODEL_NAME
)
# Extracted embeddings
embeddings = [data["embedding"] for data in response["data"]]
df["embeddings"] = embeddings
df.to_csv("embeddings.csv")

In [7]:
import numpy as np
import pandas as pd

df = pd.read_csv("embeddings.csv", index_col=0)
df["embeddings"] = df["embeddings"].apply(eval).apply(np.array)
df

,text,embeddings
0,"A young woman in her early 20s, Emily is an as...","[-0.01690799556672573, -0.0075475238263607025,..."
1,"A middle-aged man in his 40s, Jack is a succes...","[0.006835197098553181, -0.019300920888781548, ..."
2,"A woman in her late 30s, Alice is a warm and n...","[0.004433026071637869, -0.004276566207408905, ..."
3,"A man in his 50s, Tom is a retired soldier and...","[0.01690339483320713, -0.008678719401359558, 0..."
4,"A woman in her mid-20s, Sarah is a free-spirit...","[-0.01835668459534645, -0.02156326174736023, 7..."
5,"A man in his early 30s, George is a charming a...","[-0.02232372760772705, -0.008801703341305256, ..."
6,"A woman in her late 20s, Rachel is a shy and i...","[-0.005023646168410778, -0.006127253174781799,..."
7,"A man in his 60s, John is a retired professor ...","[0.022159453481435776, -0.010995248332619667, ..."
8,"A middle-aged Latina woman in her 40s, Maria i...","[-0.007437407970428467, -0.0008923872373998165..."
9,"A young African American man in his early 20s,...","[0.0017888408619910479, -0.01861933246254921, ..."
10,"A white man in his mid-30s, Tyler is a tough-a...","[0.011377423070371151, -0.03837546333670616, -..."
11,"A white woman in her late 20s, Sonya is a free...","[0.006572324316948652, -0.023054299876093864, ..."
12,"A middle-aged Hispanic man in his 50s, Manuel ...","[-0.012687166221439838, -0.011093770153820515,..."
13,"A white man in his early 40s, Will is a succes...","[-0.0014554370427504182, -0.03319186717271805,..."
14,"A young Australian woman in her mid-20s, Mia i...","[-0.01383134350180626, -0.014120866544544697, ..."
15,"A middle-aged Australian man in his 40s, Lucas...","[-0.002326435875147581, -0.0072756377048790455..."
16,A young Indigenous Australian woman in her ear...,"[-0.018001776188611984, -0.010959867388010025,..."
17,"A white Australian man in his late 20s, Max is...","[-0.0035585961304605007, -0.02702031284570694,..."
18,"A middle-aged Australian woman in her 50s, Ava...","[-0.003969918936491013, 0.00039950452628545463..."
19,A seasoned performer with a larger-than-life p...,"[-0.027581049129366875, -0.014322977513074875,..."
20,"A young up-and-coming performer, Johnny is ful...","[-0.03351768106222153, -0.016096794977784157, ..."
21,"A sultry and dramatic performer, Sable exudes ...","[-0.027877070009708405, -0.014728999696671963,..."
22,"A bubbly and vivacious performer, Dolly is a f...","[-0.03726092353463173, -0.016831299290060997, ..."
23,"A fierce and competitive performer, Vixen is a...","[-0.03409730643033981, -0.021634608507156372, ..."
24,"A chameleon-like performer, Karma is known for...","[-0.0010143282124772668, -0.008682451210916042..."
25,"A quirky and imaginative performer, Crystal is...","[-0.01535361260175705, -0.010734406299889088, ..."
26,A confident and charismatic marketing executiv...,"[-0.006515007931739092, -0.010522991418838501,..."
27,"A charming and successful entrepreneur, Marcus...","[-0.015545242466032505, -0.029111038893461227,..."
28,A kind and compassionate nurse with a heart of...,"[-0.0330631323158741, -0.019892379641532898, -..."
29,"A handsome and athletic personal trainer, Jame...","[-0.029973113909363747, -0.0038027563132345676..."
30,"A fun-loving and adventurous travel blogger, S...","[0.011128876358270645, -0.006624644622206688, ..."
31,"A quirky and creative graphic designer, Noah i...","[-0.026094067841768265, -0.01126940082758665, ..."
32,"A driven and ambitious attorney, Chloe is alwa...","[-0.011660258285701275, -0.003112336853519082,..."
33,"A laid-back and easygoing firefighter, Jake is...","[-0.019608087837696075, -0.01590844802558422, ..."
34,A charming and handsome prince who has recentl...,"[-0.009671040810644627, -0.01610550656914711, ..."
35,A mysterious and alluring woman who runs a loc...,"[0.010688669979572296, -0.003580312477424741, ..."
36,A wealthy and arrogant nobleman who loves to f...,"[-0.022395337000489235, -0.015955019742250443,..."
37,A fiery and passionate young woman who works a...,"[-0.016094282269477844, -0.02266494184732437, ..."
38,A charming and charismatic young man who is of...,"[-0.01756141521036625, -0.012982478365302086, ..."
39,A pompous and self-important nobleman who is h...,"[-0.013213041238486767, -0.03508158028125763, ..."
40,A wealthy and beautiful noblewoman who has rec...,"[-0.017838146537542343, -0.02841407246887684, ..."
41,A drunken and lecherous knight who loves nothi...,"[-0.00695203710347414, -0.03914862126111984, -..."
42,A pompous and self-righteous steward in Lady O...,"[-0.015048564411699772, -0.03204306215047836, ..."
43,A plucky and resourceful young woman who is sh...,"[-0.015487462282180786, -0.046731844544410706,..."
44,A dim-witted and gullible nobleman who is brou...,"[-0.028927011415362358, -0.03162651136517525, ..."
45,Lady Olivia's cunning and quick-witted maid. B...,"[-0.015120456926524639, -0.02327888458967209, ..."
46,"Viola's twin brother, who is also shipwrecked ...","[-0.009330138564109802, -0.045744482427835464,..."
47,A jester and musician who works in Lady Olivia...,"[-0.016434025019407272, -0.028217654675245285,..."
48,A sea captain who rescues Sebastian from the s...,"[-0.003940078429877758, -0.039967842400074005,..."
49,A plucky and resourceful young woman who works...,"[-0.03141229972243309, -0.01931467093527317, -..."
50,A good-natured and affable young man who also ...,"[-0.01864185556769371, -0.009423496201634407, ..."
51,The pious and stern minister of the local chur...,"[-0.003492253366857767, -0.01985476166009903, ..."
52,The charismatic and dashing captain of the loc...,"[-0.014173907227814198, -0.009801390580832958,..."
53,The matriarch of the wealthiest family in Will...,"[-0.028886109590530396, -0.009683411568403244,..."
54,The bumbling and absent-minded patriarch of th...,"[-0.017228592187166214, -0.008510509505867958,..."

## Custom Query Completion

In the cells below,I have composed a custom query using the chosen dataset and retrieved results from an OpenAI `Completion` model.

In [24]:
def answers(question):
    
    response = openai.Embedding.create(
    input=question,
    engine=EMBEDDING_MODEL_NAME
    )
    # Extracted the embeddings from the response
    q_embeddings = response['data'][0]["embedding"]
    
    #Finding cosine distance
    distances = distances_from_embeddings(q_embeddings,df["embeddings"].values,distance_metric="cosine")
    df["distances"] = distances
    df.sort_values(by="distances", ascending=True, inplace=True)

    #Creating the prompt
    tokenizer = tiktoken.get_encoding("cl100k_base")
    token_limit = 1000
    prompt_template = """
    Answer the question based on the context below, and if the 
    question can't be answered based on the context, say 
    "I don't know"

    Context: 

    {}

    ---

    Question: {}
    Answer:"""
    token_count = len(tokenizer.encode(prompt_template) + tokenizer.encode(question))
    # list to store text for context
    context_list = []

    # Loop over rows of the sorted dataframe
    for text in df["text"].values:
        if token_count<token_limit:
            token_count = token_count + len(tokenizer.encode(text))
        # Append text to context_list if there is enough room
            context_list.append(text)

    #string formatting to complete the prompt
    prompt = prompt_template.format(
        "\n\n###\n\n".join(context_list),
        question
        )
    
    #Querying the model
    response = openai.Completion.create(prompt=prompt,model=COMPLETION_MODEL_NAME, max_tokens=150)
    answer = response['choices'][0]['text']
    return answer

In [31]:
from openai.embeddings_utils import distances_from_embeddings
import tiktoken
EMBEDDING_MODEL_NAME="text-embedding-ada-002"
COMPLETION_MODEL_NAME = "gpt-3.5-turbo-instruct"
while True:
    # Checking for user input to exit the loop
    user_input = input("Enter question or 'exit' to quit: ")
    if user_input.lower() == 'exit':
        print("Exiting the program...")
        break  # Exit the loop if user enters 'exit'
    else:
        final=answers(user_input)
        print(f"Answer:{final}\n")

Enter question or 'exit' to quit: Whom is tom is relationship with?
Answer: Tom is in a relationship with Rachel.

Enter question or 'exit' to quit: exit
Exiting the program...

## Custom Performance Demonstration

 In the cells below, demonstrated the performance of custom query using at least 2 questions. For each question, the answer from a basic `Completion` model query as well as the answer from custom query.

### Question 1

In [29]:
Question1 = """Whom is tom is relationship with?"""

initial_answer1 = openai.Completion.create(
    model="gpt-3.5-turbo-instruct",
    prompt=Question1,
    max_tokens=150
)["choices"][0]["text"].strip()

custom_answer1=answers(Question1)

In [30]:
print(f"""{Question1}

Original Answer: {initial_answer1}
Custom Answer:   {custom_answer1}

""")

Whom is tom is relationship with?

Original Answer: I am sorry, I am an AI and I do not have access to information about specific individuals or their personal relationships. Therefore, I am unable to answer your question.
Custom Answer:    Rachel

### Question 2

In [27]:
Question2 = """What is George's age?"""

initial_answer2 = openai.Completion.create(
    model="gpt-3.5-turbo-instruct",
    prompt=Question2,
    max_tokens=150
)["choices"][0]["text"].strip()

custom_answer2=answers(Question2)

In [28]:
print(f"""{Question2}

Original Answer: {initial_answer2}
Custom Answer:   {custom_answer2}

""")

What is George's age?

Original Answer: I don't have enough information to determine George's age. Please provide more context.
Custom Answer:    Early 30s.